services:
  mysql:
    image: mysql:8.0.31
    container_name: deadline-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app", "-ppass"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - deadline-network

volumes:
  mysql-data:
